# fly.toml app configuration file generated for flytest1-ijqykw on 2025-03-08T22:14:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flytest1-ijqykw'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
